### ISSUE TITLE
Config File missing

### ISSUE THREAD

**Issue by mcalisterkm** [pi3g/bme68x-python-library#7]
The bsec config is missing from the source files, and as a result when I run any of the BSEC examples a missing file error is generated ,and the IAQ value remains unchanged at 25 with accuracy at 0.

I believe it is this line in bme68xmodule.c that is raising the error. 
 `const char *bsec_conf_path =     "BSEC_2.0.6.1_Generic_Release_04302021/config/bsec_sel_iaq_33v_4d/2021_04_29_02_51_bsec_h2s_nonh2s_2_0_6_1 .config";`

There is no such file in this repository.
In the BSEC library from Bosch the configuration folder has a number of predefined configurations 
 bsec_serialized_configurations_selectivity (.h and .c) 

Perhaps the "bsec_sel_iaq_33v_4d" example "bsec_config_selectivity[2277]" array of ints could be added as a default configuration in  bme68xmodule.c.  

Regards
Keith

**Comment by nkatanaa** [comment]
Did you download the licensed BSEC2.0 library from BOSCH and unzip to the bme68x-python-library-main folder?

**Comment by mcalisterkm** [comment]
Yes of course.
I see that the issue is fixed in the 'Meat and Cheese' version.
Also there is much better BSEC support.

Keith
